return {
  lazy = true,
  'Civitasv/cmake-tools.nvim',
  cmd = {
    'CMakeBuild',
    'CMakeBuildCurrentFile',
    'CMakeClean',
    'CMakeCloseExecutor',
    'CMakeCloseRunner',
    'CMakeGenerate',
    'CMakeInstall',
    'CMakeLaunchArgs',
    'CMakeOpenCache',
    'CMakeOpenExecutor',
    'CMakeOpenRunner',
    'CMakeQuickBuild',
    'CMakeQuickRun',
    'CMakeQuickStart',
    'CMakeRun',
    'CMakeRunCurrentFile',
    'CMakeRunTest',
    'CMakeSelectBuildDir',
    'CMakeSelectBuildPreset',
    'CMakeSelectBuildTarget',
    'CMakeSelectBuildType',
    'CMakeSelectConfigurePreset',
    'CMakeSelectCwd',
    'CMakeSelectKit',
    'CMakeSelectLaunchTarget',
    'CMakeSelectTestPreset',
    'CMakeSettings',
    'CMakeShowTargetFiles',
    'CMakeStopExecutor',
    'CMakeStopRunner',
    'CMakeTargetSettings'
  },
  opts = {}
}
