-- return {
--   'nvim-treesitter/nvim-treesitter',
--   ft = { "go", "lua", "javascript", "python", "java", "typescript", "tsx", "html", "css", "cmake", "properties", "jproperties", "yml", "yaml" },
--
--   build = ':TSUpdate',
--   opts = {
--     ensure_installed = { 'lua', 'vim', 'vimdoc' },
--     highlight = { enable = true },
--     sync_install = false,
--     indent = { enable = true, additional_vim_regex_highlighting = false, },
--   },
-- }
return {}
